### PR TITLE
Defer check for valid django.template.backends.django.DjangoTemplates

### PR DESCRIPTION
**Pull request by PamelaM**
Until `django.template.backends.django` has been imported.

### CODE REVIEW

**Comment by nedbat** [comment]
Nice commit message :)   I made you a collaborator if you want to merge these yourself.  Looks good to me: :+1:

**Comment by PamelaM** [comment]
Classic working at home commit message:
 1. Plan to type out "Fix bug that... etc"
 2. Type "Fix bug" 
 3. Get interrupted
 4. Hit return
 5. Say "D'oh!" :)

**Comment by PamelaM** [comment]
This will fix the immediate issue (the travis tests pass, except for django10tip because someone checked in a py3-only reference to lru_cache).  So I'm merging.

I _think_ we can create a new release that will fix most of the normal cases, but might still cause problems with projects that don't use DjangoTemplates but still use some other templating system.

I've got a test_project kind of in place, but I want to automate it's creation so that it will work with all supported django versions.  I need to add a testing-only dependency on jinja2 or some even more obscure template engine to confirm that the plugin works in the face of `django.template.backends.django`  _never_ getting imported, but a template file attempts to get coverage, etc.

**Comment by nedbat** [comment]
Find me on IRC if you want to talk through any of that stuff. If not, charge on! :)

**Pull request merged**
