### PR TITLE
Add test with non-unicode text file

### PR DESCRIPTION
**Pull request by jaap3**
Added a test that demonstrates the behavior reported in issue #78

Not sure how to fix this, so I'll keep this PR as a draft. Any guidance on how to "fix" this would be much appreciated.

### CODE REVIEW

**Comment by nedbat** [comment]
Can you give me a small example of a Django project using a non-utf8 template?

**Comment by jaap3** [comment]
Hi Ned. As mentioned in the original issue (#78), in my case it's not actually a template but a `changelog.txt` file tucked away in a `static` directory of a submodule. `django_coverage_plugin` finds it (with the default settings) and stops working because of the encoding error.

As you said:

> We should be more robust in the face of these sorts of things.

I'd like `django_coverage_plugin` to at least continue operating when it encounters a unreadable file. An acceptable solution would be to just mark the file as unreadable/uncovered.

**Comment by jaap3** [comment]
I've updated the test to more accurately show when/where the issue arises. I've also added a proposed fix.

**Comment by jaap3** [comment]
Fixed in #83

**Pull request closed without merging**
