### PR TITLE
Fix #20 -- Allow multiple DTL engines.

### LINKED ISSUE #20: Add support for multiple instances of the `django.template.backends.django.DjangoTemplates`.
At the moment a `ValueError` is raised as soon as `TEMPLATES` contain more than a single entry.

AFAIK this plugin already supports multiple `TEMPLATES` entries as long as they all use the `DjangoTemplates` backend.

### PR DESCRIPTION
**Pull request by charettes**
Multiple engines should be supported as long as they all use DTL.

### CODE REVIEW

**Comment by charettes** [comment]
Is this missing anything to be merged?

**Comment by nedbat** [comment]
Sorry, my attention has mostly been elsewhere recently.  
I don't have personal experience with multiple template engines.  Right now, the code will refuse to work if you have two Django template backends, and one of them is not debug-enabled.  Is that reasonable?
Can we add some tests for the multiple-engine case?

**Comment by charettes** [comment]
> Sorry, my attention has mostly been elsewhere recently.

No worries!

> I don't have personal experience with multiple template engines.

They are useful if you want to define different set of built-ins and/or context processors for specific use cases. For example, in a specific project I use the `default` engine as usual and define a `restricted` aliased engine to allow the rendering of some user provided templates.

> Right now, the code will refuse to work if you have two Django template backends, and one of them is not debug-enabled.

Unsure how we should handle this case. IMHO we shouldn't crash if template debugging is turned off even if only one engine is configured. I think raising a `RuntimeWarning` (using `warnings.warn`) for each configured backend would be more appropriate but this is something that can be done in another commit/PR. Thoughts?

> Can we add some tests for the multiple-engine case?

I'll add them right now.

**Comment by charettes** [comment]
Added test for multiple template engines.

**Comment by nedbat** [comment]
Thanks, this is version 1.3! :)

**Comment by nedbat** [comment]
(btw, I made some adjustments to the tests)

**Comment by charettes** [comment]
Thanks Ned!

**Pull request merged**
